services:
  backend:
    image: kushirot/koxs:backend
    container_name: backend-koxs
    restart: always
    depends_on:
      banco:
        condition: service_healthy
    expose:
      - "5000"
    networks:
      - koxs
    volumes:
      - ./downloads:/app/downloads

  banco:
    image: mysql:latest
    container_name: banco-koxs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: koxs
    volumes:
      - banco-koxs:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Script de inicialização
    ports:
      - "7001:3306"
    networks:
      - koxs
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    image: kushirot/koxs:frontend
    container_name: frontend-koxs
    restart: always
    ports:
      - "6050:6050"
    depends_on:
      - backend
    networks:
      - koxs
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  banco-koxs:

networks:
  koxs:
    driver: bridge
